version: "2.4"

services:

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    expose:
      - 3000
    ports:
      - '3000:3000'
    volumes:
      - ./appdata/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    expose:
      - 1883
      - 80
    ports:
      - '1883:1883'
    volumes:
      - ./appdata/mosquitto/config:/mosquitto/config
      - ./appdata/mosquitto/www:/mosquitto/www
      - ./appdata/mosquitto/data:/mosquitto/data
      - ./appdata/mosquitto/log:/mosquitto/log

  nodered:
    image: nodered/node-red
    container_name: nodered
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    expose:
      - 1880
    ports:
      - '1880:1880'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./appdata/nodered-data:/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    expose:
      - 5050
    ports:
      - '5050:5050'
    volumes:
      - ./appdata/pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=5050

  timescale:
    image: timescale/timescaledb:latest-pg16
    container_name: timescale
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    expose:
      - 5432
    ports:
      - '5432:5432'
    volumes:
      - ./appdata/timescale:/var/lib/postgresql/
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}